name: Copy main

on:
  push:
    branches: [main-dest]
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copy-main:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main-dest
      - name: Copy main
        run: |
          git clone . cl
          git -C cl push --force https://xtexx:"$GH_TOKEN"@github.com/xtexx/central.git HEAD:main
